### ISSUE TITLE
User experience suggestion.

### ISSUE THREAD

**Issue by xy172** [Wooza/ProspectTogether#9]
Currently if you close out of the GUI then toggle the ProspectTogether filter on the left of the map the gui does not return unlike Prospecting Layer does. The command brings it back but I had to look it up, feels more intuitive for that filter to bring it back if closed.

**Comment by Wooza** [comment]
Fixed in [v1.4.0-rc.1](https://github.com/Wooza/ProspectTogether/releases/tag/v1.4.0-rc.1)
